# Connection Pool, javax.mail
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
      username: ENC(PbYuQOWxH3Dprnmi10+V5w==)
      password: ENC(hyvefRvX9TrtOrhxt5gctA==)
  mail: 
    host: smtp.gmail.com
    port: 587
    username: ENC(7xVTVXSPJ0LbsxDb54e9mkMfySlYK0nGT1JkxJ4/Vrg=)
    password: ENC(cunurzG51AhjCwU8aPD40bnkJnmjvjIxK5tz9ZQ9ju8=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  main:
#    web-application-type: none  # Do not user embeded tomcat
        
# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml
#  type-aliases-package: com.gdu.myhome.dto
  
# character encodibng
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800
  port: 8080      #tomcat port 번호
  
# jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
      
    